name: Prod - build & deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/mms
  AZURE_CONTAINER_APP: mms
  AZURE_RESOURCE_GROUP: rg-mms-prod-polandcentral
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  generate_version:
    name: Generate semantic version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            filter: blob:none
      - name: Generate semantic version
        id: semantic-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "/!:|BREAKING CHANGE:/"
          minor_pattern: "/feat(\\(.+\\))?:/"
          version_format: 'v${MAJOR}.${MINOR}.${PATCH}'
      - name: Output semantic version
        run: |
          echo "Semantic version: ${{ steps.semantic-version.outputs.version }}"
  build_code:
    name: Build code
    needs: [generate_version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '25'
      - name: Run gradle build
        run: |
          VERSION="${{ needs.generate_version.outputs.version }}"
          VERSION="${VERSION#v}"
          ./gradlew build -PappVersion="$VERSION"
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: mms-jar
          path: build/libs/mms-app.jar
  build_image:
    name: Build and push Docker image
    needs: [generate_version, build_code]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: mms-jar
          path: build/libs
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build \
           -t ${{ env.DOCKER_IMAGE }}:${{ needs.generate_version.outputs.version }} \
           -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
           -t ${{ env.DOCKER_IMAGE }}:latest \
           .
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ needs.generate_version.outputs.version }}
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          docker push ${{ env.DOCKER_IMAGE }}:latest
  deploy:
    name: Deploy
    needs: [build_image]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            allow-no-subscriptions: false
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
            resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
            containerAppName: ${{ env.AZURE_CONTAINER_APP }}
            imageToDeploy: ${{ env.DOCKER_IMAGE }}:${{ needs.generate_version.outputs.version }}
            registryUrl: docker.io
            registryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
            registryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
  create_tag:
    name: Create Git tag
    needs: [deploy]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Git tag
        run: |
          git tag ${{ needs.generate_version.outputs.version }}
          git push origin ${{ needs.generate_version.outputs.version }}