name: Validate pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build_code:
    name: Build and test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '25'
      - name: Run gradle build
        run: ./gradlew build